<?php

if (!defined('dashboard')) define('dashboard','Dashboard');
if (!defined('shortcuts')) define('shortcuts','Shortcuts');
if (!defined('shortcut')) define('shortcut','Shortcut');
if (!defined('users')) define('users','Users');
if (!defined('user')) define('user','User');
if (!defined('logout')) define('logout','Logout');
if (!defined('add')) define('add','Add');
if (!defined('search')) define('search','Search');
if (!defined('surname')) define('surname','Surname');
if (!defined('firstname')) define('firstname','Firstname');
if (!defined('your_search')) define('your_search','Your search...');
if (!defined('add_shortcut')) define('add_shortcut','Add shortcut');
if (!defined('add_user')) define('add_user','Add user');
if (!defined('create')) define('create','Create the');
if (!defined('modified')) define('modified','and modified the');
if (!defined('close')) define('close','Close');
if (!defined('delete')) define('delete','Delete');
if (!defined('save')) define('save','Save');
if (!defined('password')) define('password','Password');
if (!defined('password_confirmation')) define('password_confirmation','Password confirmation');
if (!defined('reset_password')) define('reset_password','Reset password');
if (!defined('reset')) define('reset','Reset');
if (!defined('permission_to_access')) define('permission_to_access','Permission to access');
if (!defined('language')) define('language','Language');
if (!defined('created_by')) define('created_by','Created by');
if (!defined('history')) define('history','Historique');
if (!defined('country')) define('country','Country');
if (!defined('zip')) define('zip','Zip');
if (!defined('no_results')) define('no_results','No results...');
if (!defined('delete_definitively')) define('delete_definitively','delete definitively');
if (!defined('confirmation_delete_shortcut')) define('confirmation_delete_shortcut','Are you sure you want to delete the shortcut?');
if (!defined('confirmation_delete_user')) define('confirmation_delete_user','Are you sure you want to delete the user?');